version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    # Use quotes because of the space in "Module 4"
    - requirements: "Module 4/requirements.txt"

sphinx:
  # Use quotes because of the space in "Module 4"
  configuration: "Module 4/docs/source/conf.py"