version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    # Use quotes to handle the space if you didn't rename the folder
    - requirements: "Module 4/requirements.txt"

sphinx:
  # Use quotes to handle the space if you didn't rename the folder
  configuration: "Module 4/docs/source/conf.py"