services:
  db:
    image: postgres:15
    container_name: module6-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: applicant_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d applicant_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: module6-rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app-network

  web:
    build: ./src/web
    container_name: module6-web
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  worker:
    build: ./src/worker
    container_name: module6-worker
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge