version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# This is the "magic" part for nested folders
python:
  install:
    - requirements: "Module 4/requirements.txt"

sphinx:
  configuration: "Module 4/source/conf.py"